# Generated by Django 4.2.13 on 2024-06-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio1',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio2',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
