# Generated by Django 4.2.13 on 2024-06-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_hamburguesa_precio1_alter_hamburguesa_precio2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nota',
            new_name='note',
        ),
    ]
