# Generated by Django 4.2.13 on 2024-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_nota_pedido_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(default=0),
        ),
    ]
