# Generated by Django 4.2.13 on 2024-06-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_pedido_options_pedido_estado_alter_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento', max_digits=5)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el descuento está activo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.pedido')),
            ],
        ),
    ]
