# Generated by Django 4.2.13 on 2024-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='descuento',
            name='cantidad_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descuento',
            name='cantidad_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='descuento',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
