# Generated by Django 4.2.13 on 2024-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_descuento_activo_remove_descuento_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
