# Generated by Django 4.2.13 on 2024-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_descuento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
