# Generated by Django 4.2.13 on 2024-06-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_descuento_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='nombre',
            new_name='nombre_descuento',
        ),
    ]
