# Generated by Django 4.2.13 on 2024-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_rename_nombre_descuento_nombre_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cuenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
