# Generated by Django 4.2.13 on 2024-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_remove_pedido_descuento_aplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cuenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
