# Generated by Django 4.2.13 on 2024-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_alter_pedido_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cuenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
