# Generated by Django 4.2.13 on 2024-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_alter_pedido_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
